### ISSUE TITLE
Norm book fails to build in Docker

### ISSUE THREAD

**Issue by moigagoo** [pietroppeter/nimib#160]
Hi!

I couldn't find a better description for the problem I'm having. I hope you'll help me debug the issue.

So I have a book for Norm: https://github.com/moigagoo/norm/tree/develop/book

This used to build on CI but fails now. I tried building it locally, and it works on my Linux. But in Docker, I'm getting this weird error that apparently has to do JsCode compilation.

The weird part is that I'm random getting errors with random files. Sometimes it's config.nim, sometimes it's customDatatypes.nim, sometimes it's rows.nim. Common thing about them is that they both import tutorial/tables.nim.

Here's an example of an error I'm getting:

> Error: unhandled exception: cannot open file stream: tutorial/rows.log [IOError]

This particular one occurs on the CI: https://github.com/moigagoo/norm/actions/runs/3673639930/jobs/6210939015#step:3:539 

This makes me think there's a race happening. Since the pages are build concurrently, this sounds like a reasonable hypothesis.

**Comment by pietroppeter** [comment]
There is an issue with nimibook parallel builds and indeed with scinim/getting-started we used a previous commit. This should be an issue in nimibook instead of nimib. At the moment I can't but I later I can point you to exact issue and the commit to refer to (unless you find it yourself :)). As far as I understand this issue comes up when there is an actual failure and hides the error message for the failure.

**Comment by pietroppeter** [comment]
Here is the PR in scinim that uses a previous commit in nimibook: https://github.com/SciNim/getting-started/pull/50 Inwould suggest you do the same for Norm. We should then fix the issue and make another release (actually before that I probably should make a release reverting the async commit)

**Comment by moigagoo** [comment]
Thanks for the quick response! That helped.
