### ISSUE TITLE
Supports mdbook theme

### ISSUE THREAD

**Issue by Clonkk** [pietroppeter/nimib#40]
As written in the README, I just openend an issue to show support in this idea.

I think supporting the creation of docbook entirely in Nim would be really useful for bigger projects.

**Comment by Clonkk** [comment]
I'm linking our discussion at SciNim that relate (loosely) to nimib and having a mdbook theme : https://github.com/SciNim/getting-started/issues/1

**Comment by pietroppeter** [comment]
most interesting resources from mdbook docs and repo:

* https://rust-lang.github.io/mdBook/format/theme/index.html
* https://github.com/rust-lang/mdBook/blob/master/src/theme/index.hbs

**Comment by HugoGranstrom** [comment]
The `index.hbs` is a gold mine! 🤩 Many things we could get "inspiration" from ;) One notable thing though is that they are heavily using `#if`, which if I understand it, mustache doesn't support. So they'd need to be handled in a more dynamic way I guess? But at the same time, most of them seem unnecessary, either because they could be on by default or because we have other ways of handling a few of them. 
The most important part is the sidebar though, and it seems easy enough. It seems like we would only have to move the `left` partial (if we want to use it) above `> header` to get the layout correct. The hard part is getting it to play along with Water.css which sets a `max-width` of 800px for `body` which will have to work around: https://github.com/kognise/water.css/blob/129e255eb441f3501471893aea128b2a3530dab6/src/parts/_base.css#L9

**Comment by pietroppeter** [comment]
I think the strategy would be to throw away the default template and styling and start with that directly. Mustache does support a similar mechanism for if (and it has loops too), but as you noted, we will not need most of the stuff as a first approximation.

**Comment by HugoGranstrom** [comment]
Okay yeah, that makes sense. It's nicer to not have to do workarounds when you can tailor it to your needs from the beginning. How would a user of Nimib change between the default template and the nimBook template then? Or do you mean *throw away* as in making the nimBook theme the default?

> Mustache does support a similar mechanism for if (and it has loops too)

Oh I was stuck on the "logic-less, has no if-statements" part but it seems like *Sections* are what can be used 😮

**Comment by pietroppeter** [comment]
> How would a user of Nimib change between the default template and the nimBook template then?

put a `document.mustache` in the folder, see the WIP #43 

> Or do you mean throw away as in making the nimBook theme the default?

no, the default should still be a single page notebook

> "logic-less, has no if-statements"

yeah, I feel that sentence is a bit wishful thinking like zen of python "there should be only one way of doing it". But I guess mustache still prevents from putting logic like "if a == 1 and b == 2"...

and to be honest handlebars presents itself as logicless too (it actually seems to be an extension of mustache): https://www.npmjs.com/package/handlebars

**Comment by HugoGranstrom** [comment]
> put a document.mustache in the folder, see the WIP #43

Why am I surprised that even the `document` could be templated 🤯 Great, anything I can help with other than trying to make a "real-world" example at SciNim? 😄 

> no, the default should still be a single page notebook

Ok gotcha 👍 

> yeah, I feel that sentence is a bit wishful thinking like zen of python "there should be only one way of doing it". But I guess mustache still prevents from putting logic like "if a == 1 and b == 2"...

Yeah that's true, checking if a value exists (or is falsey) is quite a simplification of an ordinary if-statement. 
And I thought it was the casinos that was the biggest scammers but it seems to be templating engine (except they scam to our advantage) 🤣

**Comment by pietroppeter** [comment]
link: https://pietroppeter.github.io/nimib/book/index.html

**Comment by pietroppeter** [comment]
the PR implementing this in nimib was reverted (reset hard), I moved all this content to a separate repo. Final result (click github icon to reach the repo):
https://pietroppeter.github.io/nimiBook/
